FinalWebsite/presentation/WebUI/Controllers/CrewController.cs
using FinalWebsite.WebUI.View_Models;
using Microsoft.AspNetCore.Mvc;
using WebApp.Repositories.Abstract;

namespace FinalWebsite.WebUI.Controllers
{
    public class CrewController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CrewController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            HomeVM vM = new HomeVM()
            {
                Directors = await _unitOfWork.DirectorRepository.GetAllAsync(),
                Actors = await _unitOfWork.ActorRepository.GetAllAsync()
            };
            return View(vM);
        }

        public async Task<IActionResult>Detail(string name)
        {
            var actor = await _unitOfWork.ActorRepository.GetAsync(x => x.FullName == name, includes: new[] { "Movies"});
            if (actor != null)
            {
                HomeVM homeVM = new HomeVM()
                {
                    FullName = actor.FullName,
                    About = actor.About,
                    Image = actor.Image,
                    ImageFile = actor.ImageFile,
                    Movies=actor.Movies
                };
                return View(homeVM); 
            }
            else
            {
		    	var director = await _unitOfWork.DirectorRepository.GetAsync(x => x.FullName == name, includes: new[] { "Movies"});
				HomeVM homeVM = new HomeVM()
				{
					FullName = director.FullName,
					About = director.About,
					Image = director.Image,
					ImageFile = director.ImageFile,
                    Movies=director.Movies
				};
				return View(homeVM);
			}
        }
	}
}

FinalWebsite/presentation/WebUI/Controllers/MoviesController.cs
using FinalWebsite.Business.DTOs.SearchDto;
using FinalWebsite.Business.Services.Abstract;
using FinalWebsite.Data.Entities;
using FinalWebsite.DataAccess.Repositories.Abstract;
using FinalWebsite.WebUI.View_Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stripe;
using System.Security.Claims;
using System.Xml.Linq;
using WebApp.Repositories.Abstract;

namespace FinalWebsite.WebUI.Controllers
{
	public class MoviesController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IMovieService _movieService;

        public MoviesController(IUnitOfWork unitOfWork, IMovieService movieService)
        {
            _unitOfWork = unitOfWork;
            _movieService = movieService;
        }

        public async Task<IActionResult> Index()
		{
			var movies = await _unitOfWork.MovieRepository.GetAllAsync(includes: new[] { "Director", "Genre", "Actors" });
			return View(movies);
			
		}


		public async Task<IActionResult> Detail(string name)
		{
			var movie = await _unitOfWork.MovieRepository.GetAsync(x => x.Name == name, includes: new[] { "Director", "Genre", "Actors" });
			if (movie == null) { NotFound(); }
			return View(movie);
		}


		public async Task<IActionResult> Whatch(string name)
		{
            if(name == null) { NotFound(); }
            var movie = await _unitOfWork.MovieRepository.GetAsync(x => x.Name == name, includes: new[] { "Director", "Genre", "Actors" });
            if (movie == null) { NotFound(); }
            return View(movie);
		}




        public async Task<IActionResult> Search(SearchDto search)
        {
            if (string.IsNullOrEmpty(search.Name)) return RedirectToAction(nameof(Index));
            if (search.GenreId == null)
            {

                var allMovies = await _movieService.Search(search.Name);
                /*List<SearchDto> movies = allMovies.Select(movieDto => new SearchDto
				{
					MovieName = movieDto.MovieName
				}).ToList();*/
                return ViewComponent("Search");
            }

            var specificMovie = await _movieService.SearchByGenre(search.Name, search.GenreId);

            /*List<SearchVM> specificMovies = specificMovie.Select(movieDto => new SearchVM
			{
				MovieName = movieDto.Name
			}).ToList();*/

            return View(specificMovie);

        }
    }
}

FinalWebsite/presentation/WebUI/View Components/CommentViewComponent.cs
/*using FinalWebsite.Data.Entities;
using FinalWebsite.WebUI.View_Models;
using JwtExample.Data.DataAccess;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace FinalWebsite.WebUI.View_Components
{
	public class CommentViewComponent
	{
		private readonly AppDbContext _appDbContext;
		private readonly UserManager<AppUser> _userManager;

		public CommentViewComponent(AppDbContext appDbContext, UserManager<AppUser> userManager)
		{
			_appDbContext = appDbContext;
			_userManager = userManager;
		}

		public async Task<IViewComponentResult> InvokeAsync(int id)
		{
            CommentVM vm = new CommentVM();
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                vm = new CommentVM() { ProductId = id, ApplicationUserId = user.Id };
                return View(vm);
            }
            return View(vm);
        }
	}
}
*/

FinalWebsite/presentation/WebUI/Views/Movies/BuyTicket.cshtml
@using FinalWebsite.Data.Entities;

@{
    ViewData["Title"] = "BuyTicket";
    Layout = null;
}

@model ShoppingCart

<input hidden asp-for="MovieId"/>
    <div class="bg-secondary rounded h-100 p-4" style="width: 81% ">
        <h3 class="mb-4">Buy Ticket</h3>
        <form asp-action="BuyTicket" class="forms-sample" method="post" enctype="multipart/form-data">
            <div class="row">
            <div class="movie-img sticky-sb col-6">
                <img src="~/manage/img/uploads/@Model.Movie.Image" alt="" width="50%" height="50%">
              </div>
              <div class="col-6">
            <div class="form-group">
                <label asp-for="Movie.Name">Name</label>
                <input asp-for="Movie.Name" class="form-control" id="exampleInputName1" disabled>
            </div>
            <div class="form-group">
                <label asp-for="Count">Count</label>
                <input asp-for="Count" class="form-control" id="exampleInputName1" placeholder="Count">
                <span asp-validation-for="Count"></span>
            </div>
            <br />
            <div>
                <button type="submit" class="btn btn-success mr-2">Submit</button>
                <button asp-action="Detail" class="btn btn-light">Cancel</button>
            </div>
                </div>
            </div>
        </form>
    </div>

			

FinalWebsite/presentation/WebUI/Views/Movies/Detail.cshtml
@using FinalWebsite.Data.Entities;
@using FinalWebsite.WebUI.View_Models;


@{
    ViewData["Title"] = "Detail";
}
@model Movie

<div class="hero mv-single-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- <h1> movie listing - list</h1>
				<ul class="breadcumb">
					<li class="active"><a href="#">Home</a></li>
					<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
				</ul> -->
			</div>
		</div>
	</div>
</div>
<div class="page-single movie-single movie_single">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="movie-img sticky-sb">
					<img src="~/manage/img/uploads/@Model.Image" alt="">
					<div class="movie-btn">
						<div class="btn-transform transform-vertical red">
							<div><a asp-action="Whatch" asp-route-name="@Model.Name">  Watch</a></div>
						</div>
						<div >
							
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="movie-single-ct main-content">
					<h1 class="bd-hd">@Model.Name<span>@Model.Year</span></h1>
					<div class="title-hd-sm">
					</div>
					<div class="movie-tabs">
						<div class="tabs">
							<ul class="tab-links tabs-mv">
								<li class="active"><a href="#overview">Overview</a></li>
								<li><a href="#reviews"> Reviews</a></li>
								<li><a href="#cast">  Crew</a></li>
							</ul>
							<div class="tab-content">
								<div id="overview" class="tab active">
									<div class="row">
										<div class="col-md-8 col-sm-12 col-xs-12">
											<p>@Model.Description</p>
										</div>
										<div class="col-md-4 col-xs-12 col-sm-12">
											<div class="sb-it">
												<h6>Director: </h6>
												<p><a asp-controller="Crew" asp-action="Detail" asp-route-name="@Model.Director.FullName">@Model.Director.FullName</a></p>
											</div>
											<div class="sb-it">
												<h6>Writer: </h6>
												<p><a href="#">Joss Whedon,</a> <a href="#">Stan Lee</a></p>
											</div>
											<div class="sb-it">
												<h6>Actors: </h6>
												@foreach(var actor in Model.Actors)
												{
													<p><a asp-controller="Crew" asp-action="Detail" asp-route-name="@actor.FullName">@actor.FullName,</a></p>
												}
											</div>
											<div class="sb-it">
												<h6>Genres:</h6>
												<p><a href="#">@Model.Genre.Name </a></p>
											</div>
											<div class="sb-it">
												<h6>Release Date:</h6>
												<p>@Model.Year</p>
											</div>
											<div class="sb-it">
												<h6>Run Time:</h6>
												<p>@Model.RunTime min</p>
											</div>
											<div class="sb-it">
												<h6>Rating:</h6>
												<p>@Model.Rate</p>
											</div>
											<div class="ads">
												<img src="images/uploads/ads1.png" alt="">
											</div>
										</div>
									</div>
								</div>
								<div id="reviews" class="tab review">
									@*@foreach(var commet in Model.Comments)
									{
										<div class="mv-user-review-item">
											<div class="user-infor">
												<img src="images/uploads/userava3.jpg" alt="">
												<div>
													<h3>@commet.AppUser.Name</h3>
													
													<p class="time">
														@commet.Date
													</p>
												</div>
											</div>
											<p>@commet.Description</p>

										</div>
									}
									@await Component.InvokeAsync("Comment",new {id=Model.Id});*@
								</div>
								<div id="cast" class="tab">
									<div class="row">
										<div class="title-hd-sm">
											<h4>Director</h4>
										</div>
										<div class="mvcast-item">
											<div class="cast-it">
												<div class="cast-left">
													<img width="40px" height="40px" src="~/manage/img/uploads/@Model.Director.Image"/>
													<a asp-controller="Crew" asp-action="Detail" asp-route-name="@Model.Director.FullName">@Model.Director.FullName</a>
												</div>
											</div>
										</div>
										<!-- //== -->
										<div class="title-hd-sm">
											<h4>Actors</h4>
										</div>
										<div class="mvcast-item">
										@foreach(var actor in Model.Actors)
										{
											<div class="cast-it">
												<div class="cast-it">
													<div class="cast-left">
														<img width="40px" height="40px" src="~/manage/img/uploads/@actor.Image" />
															<a asp-controller="Crew" asp-action="Detail" asp-route-name="@actor.FullName">@actor.FullName</a>
													</div>														
												</div>
											</div>
										}
										</div>
										<!-- //== -->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

FinalWebsite/presentation/WebUI/Views/Movies/Index.cshtml
@using FinalWebsite.Data.Entities;
@using FinalWebsite.WebUI.View_Models;

@{
    ViewData["Title"] = "Index";
}

@*@model PaginateVM<Movie>*@
	@model List<Movie>

<div class="hero common-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>Movies</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="topbar-filter fw">
					<p>Found <span>@Model.Count() movies</span> in total</p>
				</div>

				<div class="flex-wrap-movielist mv-grid-fw">
				@foreach(var movie in Model)
				{
					<div class="movie-item-style-2 movie-item-style-1">
						<img src="~/manage/img/uploads/@movie.Image" alt="">
						<div class="hvr-inner">
							<a asp-controller="Movies" asp-action="Detail" asp-route-name="@movie.Name"> View Detail <i class="ion-android-arrow-dropright"></i> </a>
						</div>
						<div class="mv-item-infor">
							<h6><a href="#">@movie.Name</a></h6>
							<p class="rate"><i class="ion-android-star"></i><span>@movie.Rate</span> /10</p>
						</div>
					</div>

				}
				</div>
				@*@if (Model.Items.Any())
				{
					<nav aria-label="..." class="mt-3 btn-dark">
						<ul class="pagination">
							@if (Model.CurrentPage != 1)
							{
								<li class="page-item">
									<a class="page-link" asp-action="Index" asp-controller="Genre" asp-route-page="@(Model.CurrentPage-1)" tabindex="-1">Previous</a>
								</li>
							}
							@for (int i = 1; i <= Model.PageCount; i++)
							{
								<li class="page-item @(Model.CurrentPage==i ? "active" : "")"><a class="page-link" asp-action="Index" asp-controller="Genre" asp-route-page="@i">@i</a></li>
							}
							@if (Model.CurrentPage != Model.PageCount)
							{
								<li class="page-item">
									<a class="page-link" asp-action="Index" asp-controller="Genre" asp-route-page="@(Model.CurrentPage+1)">Next</a>
								</li>
							}
						</ul>
					</nav>
				}*@
			</div>
		</div>
	</div>
</div>

FinalWebsite/presentation/WebUI/Views/Movies/Search.cshtml
@using FinalWebsite.Business.DTOs.SearchDto;

@{
    ViewData["Title"] = "Search";
}

@model List<SearchDto>

<div>
    @foreach (var item in Model)
    {
        <li>@item</li>
    }
</div>

FinalWebsite/presentation/WebUI/Views/Movies/Whatch.cshtml
@using FinalWebsite.Data.Entities;

@{
    ViewData["Title"] = "Whatch";
    Layout = null;
}

@model Movie

<div class="container-fluid pt-4 px-4">
    <div class="row vh-100 bg-secondary rounded align-items-center justify-content-center mx-0">
        <div class="col-md-6 text-center">
            <video controls>
                <source src="~/manage/img/uploads/@Model.Video" type="video/mp4">
            </video>
        </div>
    </div>
</div>