FinalWebsite/presentation/WebUI/Controllers/CrewController.cs
using FinalWebsite.WebUI.View_Models;
using Microsoft.AspNetCore.Mvc;
using WebApp.Repositories.Abstract;

namespace FinalWebsite.WebUI.Controllers
{
    public class CrewController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CrewController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            HomeVM vM = new HomeVM()
            {
                Directors = await _unitOfWork.DirectorRepository.GetAllAsync(),
                Actors = await _unitOfWork.ActorRepository.GetAllAsync()
            };
            return View(vM);
        }

        public async Task<IActionResult>Detail(string name)
        {
            var actor = await _unitOfWork.ActorRepository.GetAsync(x => x.FullName == name, includes: new[] { "Movies"});
            if (actor != null)
            {
                HomeVM homeVM = new HomeVM()
                {
                    FullName = actor.FullName,
                    About = actor.About,
                    Image = actor.Image,
                    ImageFile = actor.ImageFile,
                    Movies=actor.Movies
                };
                return View(homeVM); 
            }
            else
            {
		    	var director = await _unitOfWork.DirectorRepository.GetAsync(x => x.FullName == name, includes: new[] { "Movies"});
				HomeVM homeVM = new HomeVM()
				{
					FullName = director.FullName,
					About = director.About,
					Image = director.Image,
					ImageFile = director.ImageFile,
                    Movies=director.Movies
				};
				return View(homeVM);
			}
        }
	}
}

FinalWebsite/presentation/WebUI/Controllers/ProfilController.cs
using FinalWebsite.Data.Entities;
using JwtExample.Data.DataAccess;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalWebsite.WebUI.Controllers
{
    public class ProfilController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

		public ProfilController(UserManager<AppUser> userManager)
		{
			_userManager = userManager;
		}

		public async Task<IActionResult> Index()
        {
            var user=await _userManager.GetUserAsync(User);
            return View();
        }
    }
}

FinalWebsite/presentation/WebUI/View Components/SearchViewComponent.cs
using FinalWebsite.Business.DTOs.SearchDto;
using Microsoft.AspNetCore.Mvc;
using WebApp.Repositories.Abstract;

namespace FinalWebsite.WebUI.View_Components
{
    public class SearchViewComponent : ViewComponent 
    { 

     private readonly IUnitOfWork _unitOfWork;

    public SearchViewComponent(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        SearchDto dto = new SearchDto();
        dto.Genres = await _unitOfWork.GenreRepository.GetAllAsync();
        return View(dto);
    }
}
}

FinalWebsite/presentation/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7 no-js" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 no-js" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en" class="no-js">


<head>
	<!-- Basic need -->
	<title>Open Pediatrics</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="profile" href="#">

	<!--Google Font-->
	<link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />

	<!-- Mobile specific meta -->
	<meta name=viewport content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone-no">
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
	<!-- CSS files -->
	<link rel="stylesheet" href="~/assets/css/plugins.css">
	<link rel="stylesheet" href="~/assets/css/style.css">

	<style>
		.btn-dark {
			border: none;
			background: #233a50 !important;
			height: 50px;
			color: white;
		}

		.top-search {
			background: #233a50 !important;
		}
	</style>

</head>
<body>
	<!--preloading-->
	<div id="preloader">
		<img class="logo" src="~/assets/images/logo1.png" alt="" width="119" height="58">
		<div id="status">
			<span></span>
			<span></span>
		</div>
	</div>
	<!--end of preloading-->

	<!-- BEGIN | Header -->
	<header class="ht-header">
		<div class="container">
			<nav class="navbar navbar-default navbar-custom">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header logo">
					<div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<div id="nav-icon1">
							<span></span>
							<span></span>
							<span></span>
						</div>
					</div>
					<a href="index-2.html"><img class="logo" src="~/assets/images/logo1.png" alt="" width="119" height="58"></a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav flex-child-menu menu-left">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>
						<li class="dropdown first">
							<a asp-controller="Home" asp-action="Index" class="btn btn-default dropdown-toggle lv1" >
								Home
							</a>
						</li>
						<li class="dropdown first">
							<a  asp-controller="Movies" asp-action="Index" class="btn btn-default dropdown-toggle lv1" data-hover="dropdown">
								Movies
							</a>
						</li>
						<li class="dropdown first">
							<a asp-controller="Crew" asp-action="Index" class="btn btn-default dropdown-toggle lv1" data-hover="dropdown">
								Crew
							</a>
						</li>
					</ul>
					<ul class="nav navbar-nav flex-child-menu menu-right">
						<li><a asp-controller="Account" asp-action="LogOut">Log Out</a></li>
						<li class="dropdown first">
							<a asp-controller="Profil" asp-action="Index" >
								@User.Identity.Name
							</a>
						</li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->
			</nav>

			<!-- top search form -->
			
			@*<div class="header-search d-none" style="position:relative;">
				<i class="fa-solid fa-magnifying-glass"></i>
				<input type="text" id="prsearch" placeholder="Search razer.com">
				<i class="fa-solid fa-xmark header-search-close-btn"></i>
				<div class="prdsearch" style="width:100%;max-height:300px;background:#222222;position:absolute;top:100%;left:0;overflow-y:scroll;">
				</div>
			</div>*@
			@await Component.InvokeAsync("Search");

		</div>
	</header>
	<!-- END | Header -->

	@RenderBody()
	<!-- footer section-->
	<footer class="ht-footer">
		<div class="container">
			<div class="flex-parent-ft">
				<div class="flex-child-ft item1">
					<a href="index-2.html"><img class="logo" src="~/assets/images/logo1.png" alt=""></a>
					<p>
						5th Avenue st, manhattan<br>
						New York, NY 10001
					</p>
					<p>Call us: <a href="#">(+01) 202 342 6789</a></p>
				</div>
				<div class="flex-child-ft item2">
					<h4>Resources</h4>
					<ul>
						<li><a href="#">About</a></li>
						<li><a href="#">Blockbuster</a></li>
						<li><a href="#">Contact Us</a></li>
						<li><a href="#">Forums</a></li>
						<li><a href="#">Blog</a></li>
						<li><a href="#">Help Center</a></li>
					</ul>
				</div>
				<div class="flex-child-ft item3">
					<h4>Legal</h4>
					<ul>
						<li><a href="#">Terms of Use</a></li>
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Security</a></li>
					</ul>
				</div>
				<div class="flex-child-ft item4">
					<h4>Account</h4>
					<ul>
						<li><a href="#">My Account</a></li>
						<li><a href="#">Watchlist</a></li>
						<li><a href="#">Collections</a></li>
						<li><a href="#">User Guide</a></li>
					</ul>
				</div>
				<div class="flex-child-ft item5">
					<h4>Newsletter</h4>
					<p>Subscribe to our newsletter system now <br> to get latest news from us.</p>
					<form action="#">
						<input type="text" placeholder="Enter your email...">
					</form>
					<a href="#" class="btn">Subscribe now <i class="ion-ios-arrow-forward"></i></a>
				</div>
			</div>
		</div>
		<div class="ft-copyright">
			<div class="ft-left">
				<p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
			</div>
			<div class="backtotop">
				<p><a href="#" id="back-to-top">Back to top  <i class="ion-ios-arrow-thin-up"></i></a></p>
			</div>
		</div>
	</footer>
	<!-- end of footer section-->

	<script src="~/assets/js/jquery.js"></script>
	<script src="~/assets/js/plugins.js"></script>
	<script src="~/assets/js/plugins2.js"></script>
	<script src="~/assets/js/custom.js"></script>
	<script src="~/assets/js/search.js"></script>
</body>


</html>

FinalWebsite/presentation/WebUI/Views/Shared/_MovieSearchPartial.cshtml
@using FinalWebsite.Business.DTOs.SearchDto;
@using FinalWebsite.Data.Entities;


@*@model SearchDto

<form asp-controller="Movies" asp-action="Search">
	<div class="top-search">
		<select asp-for="GenreId" asp-items="new SelectList(Model.Genres,nameof(Genre.Id),nameof(Genre.Name))">
			<option value="united">All Genres</option>
		</select>
		<input id="search" asp-for="@Model.Name" type="text" placeholder="Search for a movie, TV Show or celebrity that you are looking for">
		<button class="btn btn-dark" type="submit">Search</button>
	</div>


</form>*@

@model List<Movie>
@if (Model != null && Model.Count > 0)
{
    <table class="table w-100">
        <tbody>
            @foreach (Movie movie in Model)
            {
                <tr>

                    <td class="d-flex justify-content-center align-items-center"><img style="width:100px; height:100px;" src="~/assets/photos/products/@movie.Image" /></td>
                    <td class="pro-title d-flex justify-content-center align-items-center"><a asp-controller="Movies" asp-action="Detail" asp-route-name="@movie.Name">@movie.Name</a></td>
                </tr>
            }
        </tbody>
    </table>
}